CREATE TABLE sales (
    order_id TEXT,
    order_date TIMESTAMP,
    status TEXT,
    fulfilment TEXT,
    sales_channel TEXT,
    ship_service_level TEXT,
    style TEXT,
    sku TEXT,
    category TEXT,
    size TEXT,
    asin TEXT,
    courier_status TEXT,
    quantity INTEGER,
    currency TEXT,
    price NUMERIC(10,2),
    city TEXT,
    state TEXT,
    postal_code TEXT,
    country TEXT,
    promotion_ids TEXT,
    b2b TEXT,
    fulfilled_by TEXT,
    sales NUMERIC(12,2),
    year INTEGER,
    month INTEGER,
    weekday TEXT
);
